import type { Task } from "./types/TaskTypes";
import {
  FaTshirt,
  FaLaptop,
  FaMobileAlt,
  FaCouch,
  FaAppleAlt,
  FaBook,
  FaDumbbell,
  FaCar,
} from "react-icons/fa";

export const testTasks: Task[] = [
  {
    id: 1,
    title: "Prepare monthly sales report",
    description:
      "Analyze last month's sales and prepare the report for the board meeting.",
    category: "work",
    priority: "high",
    dueDate: new Date("2025-09-15"),
    completed: false,
    createdAt: new Date("2025-09-01T10:00:00Z"),
    updatedAt: new Date("2025-09-05T14:30:00Z"),
    assignee: {
      id: "u1",
      name: "John Doe",
      avatarUrl: "https://example.com/avatar1.jpg",
      email: "",
    },
  },
  {
    id: 2,
    title: "Grocery shopping",
    description: "Buy vegetables, fruits, and milk for the week.",
    category: "personal",
    priority: "medium",
    dueDate: new Date("2025-09-10"),
    completed: false,
    createdAt: new Date("2025-09-02T09:15:00Z"),
    assignee: {
      id: "u2",
      name: "Jane Smith",
      avatarUrl: "https://example.com/avatar2.jpg",
      email: "",
    },
  },
  {
    id: 3,
    title: "Doctor appointment",
    description: "Annual health check-up at 10:30 AM.",
    category: "health",
    priority: "high",
    dueDate: new Date("2025-09-12"),
    completed: false,
    createdAt: new Date("2025-09-03T11:00:00Z"),
    assignee: {
      id: "u3",
      name: "Alice Johnson",
      avatarUrl: "https://example.com/avatar3.jpg",
      email: "",
    },
  },
  {
    id: 4,
    title: "Read new book",
    description: "Finish reading 'Atomic Habits' by James Clear.",
    category: "personal growth",
    priority: "low",
    dueDate: new Date("2025-09-30"),
    completed: false,
    createdAt: new Date("2025-09-04T08:00:00Z"),
    assignee: {
      id: "u4",
      name: "Michael Brown",
      avatarUrl: "https://example.com/avatar4.jpg",
      email: "",
    },
  },
  {
    id: 5,
    title: "Team meeting",
    description: "Weekly sync with the development team.",
    category: "work",
    priority: "medium",
    dueDate: new Date("2025-09-09"),
    completed: true,
    createdAt: new Date("2025-09-01T09:00:00Z"),
    updatedAt: new Date("2025-09-08T16:45:00Z"),
    assignee: {
      id: "u5",
      name: "Emma Wilson",
      avatarUrl: "https://example.com/avatar5.jpg",
      email: "",
    },
  },
];

export const testCategories = [
  {
    id: "clothing",
    name: "Ropa",
    description: "Moda y vestimenta para todas las edades.",
    icon: "FaTshirt",
    color: "#3b82f6",
    size: 28,
  },
  {
    id: "electronics",
    name: "Electrónica",
    description: "Computadores, accesorios y gadgets.",
    icon: "FaLaptop",
    color: "#4b5563",
    size: 28,
  },
  {
    id: "mobiles",
    name: "Celulares",
    description: "Smartphones y dispositivos móviles.",
    icon: "FaMobileAlt",
    color: "#10b981",
    size: 28,
  },
  {
    id: "furniture",
    name: "Muebles",
    description: "Artículos para el hogar y oficina.",
    icon: "FaCouch",
    color: "#f97316",
    size: 28,
  },
  {
    id: "food",
    name: "Alimentos",
    description: "Productos frescos y comestibles.",
    icon: "FaAppleAlt",
    color: "#ef4444",
    size: 28,
  },
  {
    id: "books",
    name: "Libros",
    description: "Literatura, educación y entretenimiento.",
    icon: "FaBook",
    color: "#8b5cf6",
    size: 28,
  },
  {
    id: "sports",
    name: "Deportes",
    description: "Equipos y accesorios deportivos.",
    icon: "FaDumbbell",
    color: "#6366f1",
    size: 28,
  },
  {
    id: "automotive",
    name: "Automotriz",
    description: "Accesorios y repuestos para vehículos.",
    icon: "FaCar",
    color: "#f59e0b",
    size: 28,
  },
];

export const iconMap: Record<string, React.ElementType> = {
  FaTshirt,
  FaLaptop,
  FaMobileAlt,
  FaCouch,
  FaAppleAlt,
  FaBook,
  FaDumbbell,
  FaCar,
};

export const colorMap: Record<string, string> = {
  red: "#ef4444",
  blue: "#3b82f6",
  green: "#10b981",
  yellow: "#f59e0b",
  purple: "#8b5cf6",
  pink: "#ec4899",
  indigo: "#6366f1",
  orange: "#f97316",
  teal: "#14b8a6",
  gray: "#6b7280",
  emerald: "#059669",
  rose: "#f43f5e",
  sky: "#0ea5e9",
  amber: "#d97706",
  lime: "#65a30d",
  cyan: "#06b6d4",
};
