import type { Task } from "./types/TaskTypes";

export   const testTasks: Task[] = [
    {
      id: 1,
      title: "Prepare monthly sales report",
      description:
        "Analyze last month's sales and prepare the report for the board meeting.",
      category: "work",
      priority: "high",
      dueDate: new Date("2025-09-15"),
      completed: false,
      createdAt: new Date("2025-09-01T10:00:00Z"),
      updatedAt: new Date("2025-09-05T14:30:00Z"),
      assignee: {
        id: "u1",
        name: "John Doe",
        avatarUrl: "https://example.com/avatar1.jpg",
      },
    },
    {
      id: 2,
      title: "Grocery shopping",
      description: "Buy vegetables, fruits, and milk for the week.",
      category: "personal",
      priority: "medium",
      dueDate: new Date("2025-09-10"),
      completed: false,
      createdAt: new Date("2025-09-02T09:15:00Z"),
      assignee: {
        id: "u2",
        name: "Jane Smith",
        avatarUrl: "https://example.com/avatar2.jpg",
      },
    },
    {
      id: 3,
      title: "Doctor appointment",
      description: "Annual health check-up at 10:30 AM.",
      category: "health",
      priority: "high",
      dueDate: new Date("2025-09-12"),
      completed: false,
      createdAt: new Date("2025-09-03T11:00:00Z"),
      assignee: {
        id: "u3",
        name: "Alice Johnson",
        avatarUrl: "https://example.com/avatar3.jpg",
      },
    },
    {
      id: 4,
      title: "Read new book",
      description: "Finish reading 'Atomic Habits' by James Clear.",
      category: "personal growth",
      priority: "low",
      dueDate: new Date("2025-09-30"),
      completed: false,
      createdAt: new Date("2025-09-04T08:00:00Z"),
      assignee: {
        id: "u4",
        name: "Michael Brown",
        avatarUrl: "https://example.com/avatar4.jpg",
      },
    },
    {
      id: 5,
      title: "Team meeting",
      description: "Weekly sync with the development team.",
      category: "work",
      priority: "medium",
      dueDate: new Date("2025-09-09"),
      completed: true,
      createdAt: new Date("2025-09-01T09:00:00Z"),
      updatedAt: new Date("2025-09-08T16:45:00Z"),
      assignee: {
        id: "u5",
        name: "Emma Wilson",
        avatarUrl: "https://example.com/avatar5.jpg",
      },
    },
  ];